mysql:
  dns: root:@tcp(127.0.0.1:3306)/ginchat?charset=utf8mb4&parseTime=True&loc=Local
  # dns: root:123456@tcp(mysql:3308)/ginchat?charset=utf8&parseTime=True&loc=Local
redis:
  addr: "127.0.0.1:6379"
  # addr: "redis:6380"
  password: ""
  DB: 0
  poolSize: 30
  minIdleConn: 30
port:
  server: ":8081"